services:
  apigateway:
    image: apigateway
    build:
      context: ./src
      dockerfile: ./ApiGateway/Dockerfile
    ports:
      - "5000:8080"
      # - "5001:8081"
    depends_on:
      - weatherservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+:8081;http://+:8080
      # - ASPNETCORE_HTTPS_PORT=8081

  keyvaultservice:
    image: keyvaultservice
    build:
      context: ./src
      dockerfile: ./Services/KeyVaultService/Api/Dockerfile
    ports:
      - "5010:8080"
      # - "5011:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+:8081;http://+:8080
      # - ASPNETCORE_HTTPS_PORT=8081
      
      - KeyVaultUri=${KeyVaultUri}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}

  weatherservice:
    image: weatherservice
    build:
      context: ./src
      dockerfile: ./Services/WeatherService/Api/Dockerfile
    ports:
      - "5006:8080"
      # - "5007:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+:8081;http://+:8080
      # - ASPNETCORE_HTTPS_PORT=8081

  lightingservice:
    image: lightingservice
    build:
      context: ./src
      dockerfile: ./Services/LightingService/Api/Dockerfile
    ports:
      - "5020:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
